package attendance;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

//INSERT INTO `montha` (`sapid`, `1`, `2`, `3`, `4`) VALUES ('7000', '', '', '', '');

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ratho
 */
public class AttendanceMarker extends javax.swing.JFrame {

    /**
     * Creates new form AttendenceMarker
     */
    Connection c;
    Statement st;
    ArrayList<StudentDetails> list;
    int listL;
    String division;
    
    public AttendanceMarker(){
    initComponents();
    }
    
    public AttendanceMarker(String d) {
        this.division = d;
        initComponents();
        fillAtt();
        SpinnerNumberModel snm1 = new SpinnerNumberModel(1,1,10,1);
        dateSp.setModel(snm1);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        dateSp = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        mPres = new javax.swing.JButton();
        mAbs = new javax.swing.JButton();
        mSubmit = new javax.swing.JButton();
        mNA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAtt = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Date");

        jLabel2.setText("Date");

        mPres.setText("Present");
        mPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPresActionPerformed(evt);
            }
        });

        mAbs.setText("Absent");
        mAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAbsActionPerformed(evt);
            }
        });

        mSubmit.setText("Submit");
        mSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSubmitActionPerformed(evt);
            }
        });

        mNA.setText("N.A.");
        mNA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNAActionPerformed(evt);
            }
        });

        tableAtt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SAP ID", "Name", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAtt);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Batch Actions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(dateSp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(mPres)
                                            .addGap(113, 113, 113)
                                            .addComponent(mAbs)
                                            .addGap(121, 121, 121)
                                            .addComponent(mNA))))))
                        .addGap(19, 19, 19))
                    .addComponent(jSeparator2)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mAbs)
                    .addComponent(mNA)
                    .addComponent(mPres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPresActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i<listL; ++i){
            tableAtt.setValueAt("P", i, 2);
        }
    }//GEN-LAST:event_mPresActionPerformed

    private void mNAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNAActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i<listL; ++i){
            tableAtt.setValueAt("NA", i, 2);
        }
    }//GEN-LAST:event_mNAActionPerformed

    private void mAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAbsActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i<listL; ++i){
            tableAtt.setValueAt("A", i, 2);
        }
    }//GEN-LAST:event_mAbsActionPerformed

    private void mSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSubmitActionPerformed
        // TODO add your handling code here:
        //UPDATE `montha` SET `1` = 'A' WHERE `montha`.`sapid` = 5000;
        boolean flag = true;
        for(int i = 0; i<listL; ++i){
           String status = ((String) tableAtt.getValueAt(i, 2)).toUpperCase();
           if(!(status.equalsIgnoreCase("a")||status.equalsIgnoreCase("p")||status.equalsIgnoreCase("na"))){
               flag = false;
               JOptionPane.showMessageDialog(this,"Please enter a valid status");
               break;
           }
        }
        if(flag) {
            for(int i = 0; i<listL; ++i){
                long sapid = (long) tableAtt.getValueAt(i, 0);
                String status = ((String) tableAtt.getValueAt(i, 2)).toUpperCase();
                int day = (int) dateSp.getValue();
                if(division.equalsIgnoreCase("a")){
                    
                String query = "UPDATE `montha` SET `" + day  + "` = '" + status + "' WHERE `montha`.`sapid` = " + sapid + ";";
                
                try {
                    st.executeUpdate(query);
                } 
                catch (SQLException e) {
                    JOptionPane.showMessageDialog(null,e);
                }
                }
                else
                {
                    String query = "UPDATE `monthb` SET `" + day  + "` = '" + status + "' WHERE `monthb`.`sapid` = " + sapid + ";";
                try {
                    st.executeUpdate(query);
                } 
                catch (SQLException e) {
                    JOptionPane.showMessageDialog(null,e);
                }
                }
                
            }
            DashBoard d = new DashBoard();
            d.setVisible(true);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_mSubmitActionPerformed
    
    void fillAtt(){
        c = DBConnection.getDBConnection();
        try{
            st = c.createStatement();
            String command = "SELECT * FROM details" + division;
            ResultSet result = st.executeQuery(command);
//            tableAtt.setModel(DbUtils.resultSetToTableModel(result));
            list = new ArrayList();
            while(result.next()){
                long a = Long.parseLong(result.getString("sapid"));
                String n = result.getString("name");
                StudentDetails student = new StudentDetails(a,n);
                list.add(student);
            }
            listL = list.size();
            populateTable(list);
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    void populateTable(ArrayList<StudentDetails> list){
        DefaultTableModel model = (DefaultTableModel) tableAtt.getModel();
        Object rowD[] = new Object[3];
        for(int i = 0; i<listL; ++i){
            rowD[0] = list.get(i).getSapid();
            rowD[1] = list.get(i).getName();
            rowD[2] = " ";
            model.addRow(rowD);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceMarker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceMarker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner dateSp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton mAbs;
    private javax.swing.JButton mNA;
    private javax.swing.JButton mPres;
    private javax.swing.JButton mSubmit;
    private javax.swing.JTable tableAtt;
    // End of variables declaration//GEN-END:variables
}
